#!/usr/bin/php
<?php
/**
 * ACLI - Acela Command-Line Interface Tool
 */

namespace Acela\Core\ACLI;

use \Acela\Core as Core;
 
require_once __DIR__.'/Core/Core.php';

$acli = new ACLI;
$acli->run();
